/**
 * Service generator. Scaffolds a new, independently-deployable factory service
 * from an approved expansion proposal — using the same architecture as every
 * other service: pnpm workspace package, standard factory endpoints via
 * @factory/service-kit, shared contracts, MongoDB-backed, HTTP + internal token.
 *
 * No Docker, no host assumptions: the generator writes source files; the
 * devops-agent emits the Dokploy infrastructure request for manual creation.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

export interface ScaffoldOptions {
  /** kebab-case service name, e.g. "browser-testing-agent". */
  serviceName: string;
  /** capability this service provides, e.g. "browser_testing". */
  capabilityId: string;
  description: string;
  port: number;
  subdomain: string;
  /** Optional tool the service wraps (documented in README/manifest). */
  toolName?: string | null;
  /** Directory under which to create <serviceName>/. */
  servicesRoot: string;
}

export interface ScaffoldResult {
  path: string;
  files: string[];
}

function pkgJson(o: ScaffoldOptions): string {
  return JSON.stringify(
    {
      name: `@factory/${o.serviceName}`,
      version: '0.1.0',
      description: o.description,
      type: 'module',
      private: true,
      main: 'dist/index.js',
      scripts: {
        build: 'tsc -p tsconfig.json',
        start: 'node dist/index.js',
        dev: 'node --watch --import tsx src/index.ts',
        typecheck: 'tsc -p tsconfig.json --noEmit',
      },
      dependencies: { '@factory/shared': 'workspace:*', '@factory/service-kit': 'workspace:*' },
      devDependencies: { typescript: '^5.9.2', tsx: '^4.19.2', '@types/node': '^22.15.0' },
    },
    null,
    2,
  );
}

const tsconfig = `{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": { "rootDir": "src", "outDir": "dist" },
  "include": ["src/**/*.ts"]
}
`;

function manifestTs(o: ScaffoldOptions): string {
  const caps = JSON.stringify([`provide_${o.capabilityId}`, 'execute_task', 'report_result']);
  return `import { SERVICE_VERSION, type ServiceManifest } from '@factory/shared';

/** Generated by the kernel's service generator for capability "${o.capabilityId}". */
export const manifest: ServiceManifest = {
  serviceId: '${o.serviceName}',
  serviceName: '${o.serviceName}',
  serviceType: 'agent',
  version: SERVICE_VERSION,
  domain: 'https://${o.subdomain}',
  healthEndpoint: '/health',
  capabilities: ${caps},
  dependencies: ['gateway-api', 'event-bus-service', 'service-registry'],
  requiredEnv: ['MONGODB_URI', 'MONGODB_DB_NAME', 'FACTORY_INTERNAL_TOKEN'],
};
`;
}

function indexTs(o: ScaffoldOptions): string {
  return `/**
 * ${o.serviceName} — generated factory service for capability "${o.capabilityId}".
 ${o.toolName ? `* Wraps tool: ${o.toolName}.\n ` : ''}*
 * Standard factory surface (health, manifest, status, capabilities, task, logs)
 * is provided by @factory/service-kit. Replace the task handler stub with the
 * real "${o.capabilityId}" logic.
 */
import {
  loadEnv,
  BaseEnvSchema,
  MongoEnvSchema,
  connectMongo,
  EVENT_TYPES,
  startAgentRun,
  finishAgentRun,
} from '@factory/shared';
import { createFactoryService, type TaskHandler } from '@factory/service-kit';
import { manifest } from './factory/manifest.js';

const env = loadEnv(BaseEnvSchema.merge(MongoEnvSchema));

const handleTask: TaskHandler = async (req, ctx) => {
  const taskId = req.taskId ?? 'unknown';
  const runId = await startAgentRun({ agentId: manifest.serviceId, serviceId: manifest.serviceId, taskId });
  await ctx.publisher.publish({ type: EVENT_TYPES.AGENT_RUN_STARTED, taskId, payload: { agentRunId: runId, message: '${o.serviceName} received task' } });

  // TODO: implement "${o.capabilityId}" here.
  const summary = '${o.serviceName} acknowledged goal: ' + req.goal;

  await finishAgentRun(runId, { status: 'succeeded', summary });
  await ctx.publisher.publish({ type: EVENT_TYPES.AGENT_RUN_FINISHED, taskId, payload: { agentRunId: runId, message: summary } });
  return { taskId, accepted: true, agentRunId: runId, capability: '${o.capabilityId}' };
};

async function main(): Promise<void> {
  await connectMongo({ uri: env.MONGODB_URI, dbName: env.MONGODB_DB_NAME });
  const service = await createFactoryService({
    manifest,
    port: env.SERVICE_PORT,
    internalToken: env.FACTORY_INTERNAL_TOKEN,
    adminToken: env.FACTORY_ADMIN_TOKEN,
    registryUrl: env.SERVICE_REGISTRY_URL,
    eventBusUrl: env.EVENT_BUS_URL,
    logLevel: env.LOG_LEVEL,
    taskHandler: handleTask,
  });
  await service.listen();
}

main().catch((err) => {
  console.error('fatal startup error', err);
  process.exit(1);
});
`;
}

function envExample(o: ScaffoldOptions): string {
  return `NODE_ENV=development
FACTORY_ENV=local
FACTORY_INTERNAL_TOKEN=change-me-internal
FACTORY_ADMIN_TOKEN=

SERVICE_ID=${o.serviceName}
SERVICE_NAME=${o.serviceName}
SERVICE_DOMAIN=https://${o.subdomain}
SERVICE_PORT=${o.port}

SERVICE_REGISTRY_URL=http://localhost:4108
EVENT_BUS_URL=http://localhost:4111

MONGODB_URI=
MONGODB_DB_NAME=autonomous_os_kernel

LOG_LEVEL=info
`;
}

function readme(o: ScaffoldOptions): string {
  return `# ${o.serviceName}

> Generated by the kernel's service generator for capability **${o.capabilityId}**.

## Purpose
${o.description}
${o.toolName ? `\nWraps tool: **${o.toolName}**.\n` : ''}
## Standard endpoints
- \`GET /health\`
- \`GET /.factory/manifest\` · \`GET /.factory/status\` · \`GET /.factory/capabilities\`
- \`POST /.factory/task\` · \`GET /.factory/logs\`

## Deployment
Independently deployable on Dokploy. Root directory \`services/${o.serviceName}\` ·
Port \`${o.port}\` · Domain \`${o.subdomain}\`. See the infrastructure request created
for this service in the dashboard.

## Status
Scaffolded skeleton — implement the \`${o.capabilityId}\` task handler in \`src/index.ts\`.
`;
}

/** Write the scaffold to disk and return the created file list. */
export async function scaffoldService(o: ScaffoldOptions): Promise<ScaffoldResult> {
  const base = join(o.servicesRoot, o.serviceName);
  await mkdir(join(base, 'src', 'factory'), { recursive: true });

  const files: Array<[string, string]> = [
    ['package.json', pkgJson(o)],
    ['tsconfig.json', tsconfig],
    ['README.md', readme(o)],
    ['.env.example', envExample(o)],
    ['src/index.ts', indexTs(o)],
    ['src/factory/manifest.ts', manifestTs(o)],
  ];

  for (const [rel, content] of files) {
    await writeFile(join(base, rel), content, 'utf8');
  }

  return { path: base, files: files.map(([rel]) => rel) };
}
